services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: duxone
      MYSQL_USER: duxuser
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - laravel

  node:
    image: node:18
    container_name: node_build
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
